name: b2s-pytorch3d
channels:
  - pytorch3d
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.26
  - pytorch=2.4.1
  - torchvision=0.19.1
  - pytorch-cuda=12.1
  - pytorch3d=0.7.8
  - pip

